### ISSUE TITLE
Lua error in Maldraxxus and The Maw

### ISSUE THREAD

**Issue by reaper666735** [kemayo/wow-handynotes-shadowlandstreasures#1]
Hello,

like the tittle suggest i only get Lua errors when i look @ the Maldraxxus and Maw map with the addon enabled

9x ...eHandyNotes_ShadowlandsTreasures\handler.lua:167: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@HandyNotes_ShadowlandsTreasures\handler.lua"]:167: in function <...eHandyNotes_ShadowlandsTreasures\handler.lua:158>
[string "@HandyNotes_ShadowlandsTreasures\handler.lua"]:225: in function <...eHandyNotes_ShadowlandsTreasures\handler.lua:222>
[string "@HandyNotes_ShadowlandsTreasures\handler.lua"]:484: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:332: in function <HandyNotes\HandyNotes.lua:320>
[string "=[C]"]: ?
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:56: in function <HandyNotes\HandyNotes.lua:51>
[string "@HandyNotes\HandyNotes-v1.6.1.lua"]:316: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:559: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:59: in function `SetMapID'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:765: in function `NavigateToCursor'
[string "@Blizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua"]:110: in function <...lizzard_MapCanvas\MapCanvas_ScrollContainerMixin.lua:102>

**Comment by reaper666735** [comment]
small addendum, it seems that only happens if the "Use Item Icons" options is used

**Comment by kemayo** [comment]
Is it the same error in both for you? I can see why that'd happen in the Maw, but I can't see that getting triggered in Maldraxxus.

**Comment by kemayo** [comment]
Anyway, servers are still down, but I've committed ece85e95ab943e39a7abaaef00f7f1843e249b1c that should fix the Maw one at least.

**Comment by kemayo** [comment]
Okay, servers are back up so I tested it and no errors.

**Comment by reaper666735** [comment]
yeah the same error popped on both zone's :p, but anyway your v4 fix works on both ^^

**Comment by kemayo** [comment]
Excellent!
