### ISSUE TITLE
LUA errors and unable to use in-game features with this addon enabled

### ISSUE THREAD

**Issue by sarahlogic** [kemayo/wow-handynotes-shadowlandstreasures#11]
The upgrade NPCs for mythic gear won't let you update an item with this addon enabled. It will tell me I that the addon is interfering when I attempt to upgrade and then just not upgrade the item. I have to disable it every time I want to use this in-game feature. This issue has been ongoing for several months, as I constantly had to disable the addon in Korthia. There is no LUA error itself, just a popup that I need to disable the handynotes shadowlands treasures addon to properly upgrade my gear. With the addon disabled, I don't encounter any issues with this.

Also lately, it also makes it so that I can't auto-populate mythic keystone information into the LFG dungeon group finder. It will populate everything but the key level. I found this report from my buggrabber.

2x [ADDON_ACTION_BLOCKED] AddOn 'HandyNotes_ShadowlandsTreasures' tried to call the protected function 'SetEntryTitle()'.
[string "@!BugGrabber\BugGrabber.lua"]:519: in function <!BugGrabber\BugGrabber.lua:519>
[string "=[C]"]: in function `SetEntryTitle'
[string "@FrameXML\LFGList.lua"]:1144: in function `LFGListEntryCreation_SetTitleFromActivityInfo'
[string "@FrameXML\LFGList.lua"]:1013: in function `LFGListEntryCreation_OnPlayStyleSelected'
[string "@FrameXML\LFGList.lua"]:720: in function `LFGListEntryCreation_Select'
[string "@FrameXML\LFGList.lua"]:645: in function `LFGListEntryCreation_Show'
[string "@FrameXML\LFGList.lua"]:579: in function <FrameXML\LFGList.lua:567>

Thank you for your attention to this issue. Have a nice day.

**Comment by kemayo** [comment]
So, this gets reported but has never actually happened to me. I'm going to make a speculative change, but I can't really tell whether or not it'll actually *help*...

**Comment by kemayo** [comment]
Okay: either wait for a full release, or try installing the alpha. Either way, let me know if this helps.

**Comment by kemayo** [comment]
Lacking an update, I'll assume this helped. Reopen the issue if you still see the problem.
