### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Imna1975** [kemayo/wow-handynotes-shadowlandstreasures#12]
2x ...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:347: GetAchievementCriteriaInfo(achievementID, criteriaIndex [,countHidden]), criteria not found
[string "=[C]"]: in function `GetAchievementCriteriaInfoByID'
[string "@HandyNotes_ShadowlandsTreasures\handler\config.lua"]:347: in function <...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:346>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\config.lua"]:504: in function <...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:494>
[string "@HandyNotes_ShadowlandsTreasures\handler\config.lua"]:622: in function `should_show_point'
[string "@HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:977: in function `(for generator)'
[string "@HandyNotes\HandyNotes-v1.6.5-3-g5c59bd4.lua"]:435: in function `UpdateMinimapPlugin'
[string "@HandyNotes\HandyNotes-v1.6.5-3-g5c59bd4.lua"]:494: in function `?'
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ker\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@!KalielsTracker\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:1040: in function `Refresh'
[string "@HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:1036: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:1031>

**Comment by kemayo** [comment]
Huh, interesting. Can you tell me which map you were looking at?

**Comment by Imna1975** [comment]
I was in Zereth Mortis when the error came but after restarting the error didn't come back
