### ISSUE TITLE
Lua Error 

### ISSUE THREAD

**Issue by cyberbook78** [kemayo/wow-handynotes-shadowlandstreasures#14]
Message: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
Time: Wed Jun  1 08:07:27 2022
Count: 1
Stack: Usage: local sources = C_TransmogCollection.GetAppearanceSources(appearanceID, categoryType, transmogLocation)
[string "=(tail call)"]: ?
[string "=[C]"]: in function `GetAppearanceSources'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\config.lua"]:404: in function <...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:383>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\config.lua"]:318: in function <...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:316>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\config.lua"]:496: in function <...s\HandyNotes_ShadowlandsTreasures\handler\config.lua:494>
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\config.lua"]:622: in function `should_show_point'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:990: in function `(for generator)'
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:334: in function `RefreshPlugin'
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:408: in function `UpdateWorldMapPlugin'
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:495: in function `?'
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ElvUI\Libraries\Core\Ace\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `SendMessage'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:1053: in function `Refresh'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:1049: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:1044>

Locals: <none>

**Comment by kemayo** [comment]
Already fixed in #13, but I do see that my release hasn't gone through to curseforge yet, so I'll take a look at what's going on there...

**Comment by kemayo** [comment]
Okay, release should be out on curseforge now.
