### ISSUE TITLE
Bastion Treasure information

### ISSUE THREAD

**Issue by reaper666735** [kemayo/wow-handynotes-shadowlandstreasures#2]
Hello,

in bastion there is a treasure that rewards a fist weapon ( https://www.wowhead.com/item=183609/re-powered-golliath-fists?bonus=6935#comments ) ,

the addon tells us to get anima containers from random mobs in that area ( https://www.wowhead.com/item=180534/unstable-construct-anima#comments ) but in fact they are interactable containers in the camp itself you have to use :)

**Comment by kemayo** [comment]
Thanks! This is fixed now. This has been a pretty intense expansion from the standpoint of Blizzard changing up the treasure unlock requirements after beta...
