### ISSUE TITLE
Recieving 'GetFactionInfoByID' error while in Korthia

### ISSUE THREAD

**Issue by nhtwolf** [kemayo/wow-handynotes-shadowlandstreasures#20]
This is from BugSack:

24x ...ns/HandyNotes_ShadowlandsTreasures/zones/Korthia.lua:21: attempt to call global 'GetFactionInfoByID' (a nil value)
[string "@HandyNotes_ShadowlandsTreasures/zones/Korthia.lua"]:21: in function `IsActive'
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:619: in function `point_active'
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:669: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:665>
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:1333: in function `(for generator)'
[string "@HandyNotes/HandyNotes.lua"]:447: in function <HandyNotes/HandyNotes.lua:433>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:497: in function `?'
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@HereBeDragons/HereBeDragons-2.0-27.lua"]:339: in function <HereBeDragons/HereBeDragons-2.0.lua:322>
[string "@HereBeDragons/HereBeDragons-2.0-27.lua"]:369: in function <HereBeDragons/HereBeDragons-2.0.lua:368>

Locals:
point = <table> {
 achievement = 15066
 note = "Use the shrine to get {spell:352367} to see the altar path"
 criteria = 52266
 _uiMapID = 1961
 _coord = 39404270
 research = 5
 quest = 63922
 loot = <table> {
 }
}
(*temporary) = 3
(*temporary) = nil
(*temporary) = 2472
(*temporary) = "attempt to call global 'GetFactionInfoByID' (a nil value)"

------------------------------------------------------------------------------------------------------------------------------------------------
I changed the line to:
		return select(3, C_Reputation.GetFactionDataByID(2472)) >= point.research
in hopes of an easy fix but get the following error with that change:

3x ...ns/HandyNotes_ShadowlandsTreasures/zones/Korthia.lua:21: attempt to compare number with nil
[string "@HandyNotes_ShadowlandsTreasures/zones/Korthia.lua"]:21: in function `IsActive'
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:619: in function `point_active'
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:669: in function <.../HandyNotes_ShadowlandsTreasures/handler/handler.lua:665>
[string "@HandyNotes_ShadowlandsTreasures/handler/handler.lua"]:1333: in function `(for generator)'
[string "@HandyNotes/HandyNotes.lua"]:338: in function <HandyNotes/HandyNotes.lua:326>
[string "=[C]"]: ?
[string "@HandyNotes/HandyNotes.lua"]:56: in function <HandyNotes/HandyNotes.lua:51>
[string "@HandyNotes/HandyNotes.lua"]:322: in function `RefreshAllData'
[string "@HandyNotes/HandyNotes.lua"]:426: in function `UpdateWorldMap'
[string "@HandyNotes/HandyNotes.lua"]:647: in function <HandyNotes/HandyNotes.lua:638>
[string "=[C]"]: ?
[string "@HandyNotes/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <HandyNotes/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
...
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:422: in function `UIParentLoadAddOn'
[string "@Blizzard_UIParent/Mainline/UIParent.lua"]:627: in function `MajorFactions_LoadUI'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:103: in function `SetUpMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:96: in function `RefreshMajorFactionList'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:91: in function `RefreshOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:83: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:79>
[string "=[C]"]: in function `CreateFrame'
[string "@Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:49: in function `CreateOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:78: in function `RefreshExpansionOverlay'
[string "@Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:37: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:35>

Locals:
point = <table> {
 achievement = 15066
 note = "Use the shrine to get {spell:352367} to see the altar path"
 criteria = 52266
 _uiMapID = 1961
 _coord = 39404270
 research = 5
 quest = 63922
 loot = <table> {
 }
}
(*temporary) = nil
(*temporary) = 5
(*temporary) = <table> {
 hasBonusRepGain = false
 description = "Korthian attendants have committed their existence to researching relics from across the Shadowlands. Led by their Archivist, they are dedicated to recovering the relics scattered across Korthia in the wake of the mawsworn invasion."
 isHeaderWithRep = false
 isHeader = false
 currentReactionThreshold = 14000
 canSetInactive = true
 atWarWith = false
 isWatched = false
 isCollapsed = false
 canToggleAtWar = false
 nextReactionThreshold = 25000
 factionID = 2472
 name = "The Archivists' Codex"
 currentStanding = 14000
 isAccountWide = false
 isChild = false
 reaction = 4
}
(*temporary) = <table> {
 hasBonusRepGain = false
 description = "Korthian attendants have committed their existence to researching relics from across the Shadowlands. Led by their Archivist, they are dedicated to recovering the relics scattered across Korthia in the wake of the mawsworn invasion."
 isHeaderWithRep = false
 isHeader = false
 currentReactionThreshold = 14000
 canSetInactive = true
 atWarWith = false
 isWatched = false
 isCollapsed = false
 canToggleAtWar = false
 nextReactionThreshold = 25000
 factionID = 2472
 name = "The Archivists' Codex"
 currentStanding = 14000
 isAccountWide = false
 isChild = false
 reaction = 4
}
(*temporary) = "attempt to compare number with nil"

**Comment by kemayo** [comment]
Thanks! I got the core usage of that function earlier, but I missed this one-off call in my Korthia checks. I will fix that.
