### ISSUE TITLE
Defeated rare's still showing

### ISSUE THREAD

**Issue by reaper666735** [kemayo/wow-handynotes-shadowlandstreasures#3]
Hello,

so yeah basically i kill a rare and it stays on the map :p

https://imgur.com/fUxWU0A

https://imgur.com/TkgF9tM

here are 2 examples of me killing them both (green name) and staying on my map regardless, so i'm wondering if it's a bug in the "progress" check on load of the addon or some other issue ?

**Comment by kemayo** [comment]
Could I persuade you to type the following into your chat and let me know what it prints out?

```
/dump C_QuestLog.IsQuestFlaggedCompleted(57705)
/dump C_QuestLog.IsQuestFlaggedCompleted(57708)
```

Also, what faction are you?

**Comment by reaper666735** [comment]
both values came out as 'False'

and i'm alliance on those chars from the screenshots

**Comment by kemayo** [comment]
Did they disappear when you killed them and come back later, or did they just never disappear?

**Comment by reaper666735** [comment]
i do "think" they went away in my very first playthrough but ofc i was not paying massive attention on that when leveling :p

is there some other way to test that could help you out ?

**Comment by kemayo** [comment]
If you came back later, this is because all rares are dailies this expansion. So the skull on your map is appearing if it's present-and-killable-for-loot.

I've been meaning to add a preference to make the achievement authoritative.

**Comment by kemayo** [comment]
There's now a preference for making achievement-complete the only thing that counts.
