### ISSUE TITLE
updates?

### ISSUE THREAD

**Issue by Bloodson22** [kemayo/wow-handynotes-shadowlandstreasures#5]
with 9.1.5 out, i keep getting an error when trying to upgrade a piece of gear in korthia, makes me disable addon. idk how to pull any kind of error reports, was here looking to see if any others had made mention of it. just hoping there will be an update soon?

**Comment by kemayo** [comment]
I've never seen that error with the gear in korthia -- and I just tried it now. That said, I am about to release an update for general TOC-and-library stuff, so maybe there's some random unrelated thing that might have fixed it.
