### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Imna1975** [kemayo/wow-handynotes-shadowlandstreasures#6]
12x SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@SharedXML\MathUtil.lua"]:129: in function <SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2671: in function <FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
x1 = nil
y1 = nil
x2 = nil
y2 = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'y2' (a nil value)"

**Comment by kemayo** [comment]
Where were you when this happened?

**Comment by Imna1975** [comment]
world quest made in the arden forest

**Comment by Imna1975** [comment]
24x SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@SharedXML\MathUtil.lua"]:129: in function <SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2671: in function <FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
x1 = nil
y1 = nil
x2 = nil
y2 = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'y2' (a nil value)"





the error comes as soon as I open the map

**Comment by althatjaz** [comment]
Seeing the same thing as soon as I open the map.  Doesn't seem to matter which zone. Happening on all alts.  

Message: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
Time: Tue Nov 30 14:22:39 2021
Count: 1
Stack: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\SharedXML\MathUtil.lua"]:129: in function <Interface\SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
...
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

**Comment by Zenhunter** [comment]
I'm having this issue as well now. Anytime I open the Map:

Message: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y1' (a nil value)
Time: Wed Dec  1 11:13:48 2021
Count: 13
Stack: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y1' (a nil value)
[string "=[C]"]: ?
[string "@Interface\SharedXML\MathUtil.lua"]:129: in function <Interface\SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:461: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:460>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:464: in function `RefreshAllDataProviders'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:491: in function `RefreshAll'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:87: in function `OnShow'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:246: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:439>
[string "=[C]"]: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

**Comment by kemayo** [comment]
I can't make this happen myself, unfortunately, so I'll add some speculative code that might stop it.

**Comment by kemayo** [comment]
Okay, could someone who's reliably having the issue please update to the latest alpha version (found [here](https://www.curseforge.com/wow/addons/handynotes-shadowlands-treasures/files)) and let me know whether this stops the errors.

**Comment by Imna1975** [comment]
I've already installed it and haven't had any problems, but I've only been online for a short time

**Comment by althatjaz** [comment]
I'll sign on with the current version and make sure it's still happening then update.

**Comment by althatjaz** [comment]
And, of course, not it's not happening...  :/

**Comment by althatjaz** [comment]
OK, here's the error
Message: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
Time: Sun Dec  5 16:13:27 2021
Count: 1
Stack: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@Interface\AddOns\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua"]:761: in function <...Ons\TradeSkillMaster\LibTSM\Service\ErrorHandler.lua:717>
[string "=[C]"]: ?
[string "@Interface\SharedXML\MathUtil.lua"]:129: in function <Interface\SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
...
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

**Comment by althatjaz** [comment]
Did you spin a new version?  Latest I'm seeing is v33 from 11/13 which I already have loaded.

**Comment by kemayo** [comment]
This alpha [here](https://www.curseforge.com/wow/addons/handynotes-shadowlands-treasures/files/3550492) -- it wasn't approved yet when I posted the last link. :D

**Comment by althatjaz** [comment]
OK, got it.  Trying now.

**Comment by althatjaz** [comment]
Looks good, I'm not seeing the error with the new build.

**Comment by Zenhunter** [comment]
I wanted to note: I did not upgrade to the Alpha, however the add-on, TomCat's Tours updated today and I no longer have the error. Not a programmer, so not sure how this works, but could that add-on been interfering/not working with yours since they both anchor to HandyNotes (I think)?

**Comment by althatjaz** [comment]
I'm not running TomCat's Tours.

**Comment by Imna1975** [comment]
the error is there again when opening the map

Edit : I just noticed when I open the map and click a world quest the error comes up I use World Quests List. I just noticed when I deactivate the add-on the error comes immediately when I open the map

108x SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y1' (a nil value)
[string "@SharedXML\MathUtil.lua"]:129: in function <SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:461: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:460>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:464: in function `RefreshAllDataProviders'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:491: in function `RefreshAll'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:87: in function `OnShow'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:246: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2671: in function <FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
x1 = nil
y1 = nil
x2 = 1994.207275
y2 = 4534.048340
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'y1' (a nil value)"

**Comment by althatjaz** [comment]
Imna1975, I'd make sure you have the alpha build.  I don't think it was advertised yet based on the timing of your earlier note when you said you'd already installed it. kemayo share the updated link after that.

**Comment by Imna1975** [comment]
i have the current alpha version on it and it went on for a while since yesterday this error comes back

**Comment by kemayo** [comment]
@Imna1975 if you're getting the error on line 109 as `[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function Connect'` implies, then you're no longer on the alpha version, as the specific line that error could happen on is now on line 117.

If you manually installed it, whatever updater you're using might have "updated" you to the current release version...

**Comment by jnatale311** [comment]
@kemayo I was getting a similar error in korthia every time I opened the map, this error occured in the 05Dec2021 build from curseforge downloader. I resolved the issue by updating your call:

```
if pins[#pins] then
     self:ConnectPins(pins[#pins], pin, point)
end
```
to 

```
if pins[#pins] and pins[#pins] ~= nil then
     self:ConnectPins(pins[#pins], pin, point)
end
```

see below for the error:

Message: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
Time: Fri Dec 24 15:29:29 2021
Count: 1
Stack: Interface\SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Interface\AddOns\Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...ace\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:233>
[string "=[C]"]: ?
[string "=[C]"]: in function `OnMapChanged'
[string "@Interface\AddOns\Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2671: in function <Interface\FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@Interface\FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Interface\AddOns\Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

**Comment by jnatale311** [comment]
your alpha release fixed the error for me

**Comment by Imna1975** [comment]
the error has not occurred again is now running

**Comment by DockieB** [comment]
I've been getting the same error. I don't use TomCat. Error below. Just occurred in Ardenweald, but has occurred in other zones also. I'm using version 33 release date 12/05/21.

10x SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y2' (a nil value)
[string "@SharedXML\MathUtil.lua"]:129: in function <SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\MapCanvas_DataProviderBase.lua"]:76: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:580: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:579>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:583: in function `OnMapChanged'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:234: in function `OnMapChanged'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:60: in function `SetMapID'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:245: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:243>
...
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2671: in function <FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
x1 = nil
y1 = nil
x2 = nil
y2 = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'y2' (a nil value)"

**Comment by DockieB** [comment]
This was the one of the errors returned last night...

23x SharedXML\MathUtil.lua:129: attempt to perform arithmetic on local 'y1' (a nil value)
[string "@SharedXML\MathUtil.lua"]:129: in function <SharedXML\MathUtil.lua:128>
[string "=(tail call)"]: ?
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:109: in function `Connect'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:56: in function `ConnectPins'
[string "@HandyNotes_ShadowlandsTreasures\handler\routes.lua"]:41: in function `RefreshAllData'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:461: in function <...aceBlizzard_MapCanvas\Blizzard_MapCanvas.lua:460>
[string "=[C]"]: in function `secureexecuterange'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:464: in function `RefreshAllDataProviders'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:491: in function `RefreshAll'
[string "@Blizzard_MapCanvas\Blizzard_MapCanvas.lua"]:87: in function `OnShow'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:246: in function <...rfaceBlizzard_WorldMap\Blizzard_WorldMap.lua:243>
[string "=[C]"]: ?
...
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2958: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2764: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2671: in function <FrameXML\UIParent.lua:2667>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3522: in function `ShowUIPanel'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:103: in function `SetDisplayState'
[string "@FrameXML\QuestLogOwnerMixin.lua"]:41: in function `HandleUserActionToggleSelf'
[string "@Blizzard_WorldMap\Blizzard_WorldMap.lua"]:440: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
x1 = nil
y1 = nil
x2 = 1548.246948
y2 = 3578.656006
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'y1' (a nil value)"

**Comment by DockieB** [comment]
The error occurs as soon as I open the map. Just did a quick check and it's every Shadowlands zone except Oribos, Maldraxxus, and Bastion. Other xpac areas are unaffected.

**Comment by DockieB** [comment]
EDIT: the error is back 1/2/22


==================
I tried commenting here yesterday, but Curseforge was having connection issues.

The problem has been resolved. I'm not sure who/what program had an update, but something must have been updated to fix the conflict in code. All is well. Thanks for an awesome add-on!

**Comment by Comorama** [comment]
Was having this issue consistently. Updated to alpha and now I am not seeing the error. Thanks for this!

**Comment by ghost** [comment]
Similar to above comment... Was having same issue consistently, updated to @kemayo 's [alpha link](https://www.curseforge.com/wow/addons/handynotes-shadowlands-treasures/files/3550492) and no longer seeing the error.  Thanks!
