### ISSUE TITLE
LUA error when mouseover Anima Shard on in Bastion

### ISSUE THREAD

**Issue by eloxole** [kemayo/wow-handynotes-shadowlandstreasures#8]
Keep getting LUA error when mouseover Anima Shard on the world map in Bastion.

Message: ...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:468: attempt to compare nil with number
Time: Tue Mar  8 20:04:00 2022
Count: 2
Stack: ...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:468: attempt to compare nil with number
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:468: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:467>
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:527: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:483>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\HandyNotes_ShadowlandsTreasures\handler\handler.lua"]:686: in function <...\HandyNotes_ShadowlandsTreasures\handler\handler.lua:662>
[string "=[C]"]: ?
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:56: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:51>
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:166: in function `OnEnter'
[string "@Interface\AddOns\HandyNotes\HandyNotes.lua"]:391: in function <Interface\AddOns\HandyNotes\HandyNotes.lua:390>

Locals: <none>

**Comment by kemayo** [comment]
Thanks! Fixed in a7b41356f2fbd20fea509f33f80de5dcd321b0af
