### ISSUE TITLE
Need to add qualification to this Treasure.

### ISSUE THREAD

**Issue by Ploute** [kemayo/wow-handynotes-shadowlandstreasures#9]
In Shadowlands, Zereth Mortis, the Treasure: 65173, Library Vault it appears that you must have Dealic Understanding (https://www.wowhead.com/order-advancement=1932/dealic-understanding) unlocked to access this treasure. (https://www.wowhead.com/object=373543/library-vault#comments)  Thanks for all the great work.

**Comment by kemayo** [comment]
Exciting, a hotfix-notice. I wonder if they've done that to the other treasures with schematics that you can loot before knowing the relevant Understanding as well... :D
